### ISSUE TITLE
Style inline <code/> tags

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-developer#293]
See [comment](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp?node-id=2934:7370&mode=dev#566860233)

> This particular design here is to apply to the `code` tag across the site. Shown here, the Light Gray color applied as an inline code background with a 2px border radius. So pseudo code something like:

```css
code {
	...
	background: #f6f6f6; // the CSS var
	border-radius: 2px;
}
```
